name: CI

on:
  workflow_dispatch:
  push:
    paths:
      - '**'

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run compile

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [compile, lint]
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run compile

      - uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_DEPLOY_CREDENTIALS }} # FIXME: 本来は json キーではなく Workload Identity 連携を利用したほうがセキュリティ的には望ましい

      - uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: cloud-functions-ts-test
          runtime: nodejs16
          region: asia-northeast1
          entry_point: helloWorld
          service_account_email: cf-runtime@cloud-functions-test-361611.iam.gserviceaccount.com
